# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Опция')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='OptionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Параметр')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', related_query_name='option', to='catalogue.Option')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлен')),
                ('attribute', models.ManyToManyField(to='catalogue.OptionAttribute', verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImageExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
            ],
            options={
                'verbose_name': 'Extra image',
                'verbose_name_plural': 'Extra images',
            },
        ),
        migrations.CreateModel(
            name='ProductImagePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='product')),
            ],
            options={
                'verbose_name': 'Preview image',
            },
        ),
        migrations.RemoveField(
            model_name='optionitem',
            name='option_group',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product_options',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='ProductRecommendation',
        ),
        migrations.DeleteModel(
            name='ProductSpecial',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='options',
        ),
        migrations.DeleteModel(
            name='OptionGroup',
        ),
        migrations.DeleteModel(
            name='OptionItem',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.AddField(
            model_name='category',
            name='option',
            field=models.ManyToManyField(to='catalogue.Option', verbose_name='Характеристика'),
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(to='catalogue.Product', verbose_name='Товар'),
        ),
    ]
