# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20160607_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['name'], 'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AlterModelOptions(
            name='optionattribute',
            options={'ordering': ['name'], 'verbose_name': 'Аттрибут', 'verbose_name_plural': 'Аттрибуты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.ManyToManyField(blank=True, to='catalogue.Option', verbose_name='Опция'),
        ),
        migrations.AlterField(
            model_name='category',
            name='option',
            field=models.ManyToManyField(blank=True, to='catalogue.Option', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(blank=True, to='catalogue.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(blank=True, to='catalogue.OptionAttribute', verbose_name='Параметры'),
        ),
    ]
