# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20160607_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_saled',
            field=models.BooleanField(default=False),
        ),
    ]
