# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 14:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_product_is_saled'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
